name: github_users
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^13.2.4
  go_router_builder: ^2.5.1
  hydrated_bloc: ^9.1.5
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  intl: any
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  path_provider: ^2.1.3
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter_gen:
  output: lib/presentation/core/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/logo/
