name: github_users
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_screenutil: ^5.9.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^13.2.4
  go_router_builder: ^2.5.1
  injectable: ^2.4.1
  injectable_generator: ^2.6.1
  json_annotation: ^4.8.1
  kt_dart: ^1.1.0
  very_good_analysis: ^5.1.0

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
